{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rariable.fullname" . }}
  labels:
    {{- include "rariable.labels" . | nindent 4 }}
type: Opaque
stringData:
  RARIBLE_API_KEY: {{ required "secret.apiKey is required (or set secret.existingSecret)" .Values.secret.apiKey | quote }}
{{- end }}
